# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbfd15cf4b35cf78f407eb3f67be4b43509bd2ff6a98ebaa4877d23b39fadc9b0cdfc3d7027e5b450d432a9dbaa5986299281a1f57f6f69c96e155b39f789505

test:
  secret_key_base: 0b89e939b50beddd95f64c1e4bf4f7298071ef7e1325e5300a025eff5336916aad1db89ea9721ec7f10ee627d527f7c32915d78a4fb4e76441b670dd70059332

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
