# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 673b32ef8cd56a910efa621fbba317b211f00e6e86c938212798432b05bc3460880b33fe57ccdbbc40557bf1535a4d381c8ae8bbfee61a8d28cc378437a1b187

test:
  secret_key_base: c106729e5d3d55904a7e29274f0cd13d99b71a9818d0cdec714cded459f32b615b46410fbfe4ec03e0c9bf913557f5de7c42b381a93ea432965bae85c844d8aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
